### ISSUE TITLE
Error message for subcommand is wrong

### ISSUE THREAD

**Issue by yegle** [bobziuchkovski/writ#5]
$ cat test.go
```
package main

import (
        "os"

        "github.com/bobziuchkovski/writ"
)

type Foo struct {
        Bar Bar `command:"bar"`
}

type Bar struct {
        HelpFlag bool `flag:"h, help"`
}

func main() {
        foo := &Foo{}
        cmd := writ.New("foo", foo)
        path, _, err := cmd.Decode(os.Args[1:])
        if err != nil {
                path.Last().ExitHelp(err)
        }
}
```

$ go run test.go bar --help --help
```
Usage: foo bar [OPTION]... [ARG]...

Error: option "bar" specified too many times
exit status 1
```

I believe the error message should be `option "help" specified too many times`

**Comment by bobziuchkovski** [comment]
You're absolutely correct.  Thanks for the report!  I just added test coverage for the error message and fixed in master.  There's also a new v0.8.9 release tag for the fix.  When you get a chance, check-out latest master or the v0.8.9 tag and give it a go.  I've confirmed it fixes your example above and that it fixes the added tests, but want to make sure I'm not missing any other cases.

**Comment by bobziuchkovski** [comment]
This is now fixed.  Closing.
